### register
POST http://localhost:3000/api/users/register
X-API-Key : RAHASIA
Accept: application/json
Content-Type: application/json

{
    "username": "jo",
    "password": "jojo",
    "role_id": 2
}

### login
POST http://localhost:3000/api/users/login
X-API-Key : RAHASIA
Accept: application/json
Content-Type: application/json

{
    "username": "tony",
    "password": "tony123"
}

### login not admin
POST http://localhost:3000/api/users/login
X-API-Key : RAHASIA
Accept: application/json
Content-Type: application/json

{
    "username": "kenndragon",
    "password": "kennyzx"
}

###Get all user
GET http://localhost:3000/api/users/all