### register
POST http://localhost:3000/api/users/register
X-API-Key : RAHASIA
Accept: application/json
Content-Type: application/json

{
    "username": "kev",
    "password": "kevin123",
    "role_id": 1
}

### login
POST http://localhost:3000/api/users/login
X-API-Key : RAHASIA
Accept: application/json
Content-Type: application/json

{
    "username": "tony",
    "password": "tony123"
}

### login not admin
POST http://localhost:3000/api/users/login
X-API-Key : RAHASIA
Accept: application/json
Content-Type: application/json

{
    "username": "jo",
    "password": "jojo"
}

###Get all user only for admin
GET http://localhost:3000/api/users/all
X-API-Key : RAHASIA

###logout
GET http://localhost:3000/api/users/logout
X-API-Key : RAHASIA